### ISSUE TITLE
np.complex deprecated 

### ISSUE THREAD

**Issue by egcpvanloon** [TRIQS/w2dynamics_interface#3]
np.complex was deprecated in numpy 1.20.0 and expired in numpy 1.24.0, see:
https://numpy.org/doc/stable/release/1.20.0-notes.html
https://numpy.org/devdocs/release/1.24.0-notes.html

This seems to have been patched in w2dynamics itself: 
https://github.com/w2dynamics/w2dynamics/commit/a6ad6110f869a0b68336ef3514127e48e7b73b03

But when I did a clean install of the w2dynamics interface, it used a previous commit of w2dynamics (d02d8c9973fec34540061ea3ec5705bbd25bdc5b), where the patches to fix this issue have not yet been implemented.

**Comment by Wentzell** [comment]
@egcpvanloon This issue should be resolved on the unstable branch, can you confirm?

@the-hampel We should then back-port related fixes to 3.1.x.

**Comment by the-hampel** [comment]
I added the fixes to the 3.1.x branch and tested it locally. For me all tests pass now. Let me know if there are still problems.

**Comment by egcpvanloon** [comment]
Yes, on unstable it works. Thanks!
